### ISSUE TITLE
fontStyle: "oblique" Is not a valid property

### ISSUE THREAD

**Issue by albinhubsch** [zeplin/react-native-extension#13]
RN only supports [ "normal", "italic" ] as valid properties to fontStyle.

I guess this happens because of Sketch or specific fonts. However, "oblique" should be converted to "italic"

**Comment by dirtybit** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix invalid fontStyle issue in React Native extension.](https://trello.com/c/PGD2trgt/62-fix-invalid-fontstyle-issue-in-react-native-extension)

**Comment by dirtybit** [comment]
@albinhubsch Thanks for the report! It's fixed now.
