### ISSUE TITLE
Make this available on Web projects

### ISSUE THREAD

**Issue by martinmcneela** [zeplin/react-native-extension#17]
Can this extension be made available to Web projects? I am currently building a web app with styled-components and it seems like this extension would be perfect for exporting colors...etc...

But it is only available on iOS and Android.

**Comment by mertkahyaoglu** [comment]
Hi @martinmcneela,

There is a Zeplin extension for [Styled Components](https://extensions.zeplin.io/tikhon_belousko/zeplin-styled-components-extension). It might be what you need. Please take a look at it and let me know if that works for you.

**Comment by asgvard** [comment]
@mertkahyaoglu We have another use case for React Native extension and Web. For example we are using React Native Web library for cross-platform app development, which means the syntax is the same as in React Native, but our project in Zeplin is Web for the big screen TVs, so we cannot use this extension there. Is it possible to just enable it for Web projects with the same behaviour as it is now? What is the limitation of it to be only available for iOS and Android?

**Comment by SteveSchreiner** [comment]
Agreed this would be great to make this work for web projects

**Comment by skarahoda** [comment]
Hi @asgvard and @SteveSchreiner,

We have released a new version for the extension; from now on, you can use it for web projects too.

Let us know if you have any questions.

**Comment by asgvard** [comment]
@skarahoda great to hear, thank you, we will try it asap and let you know if we have any issues 🙂
