### ISSUE TITLE
Suggestion: adding an option to set single or double quotes

### ISSUE THREAD

**Issue by luispinho** [zeplin/react-native-extension#23]
Hi!
I'd like to leave a suggestion of adding the option to choose if the exported code uses single (') or double (") quotes. I suggest this since in the projects I work with use single quotes for the code  styling (and right now the default is double in the extension). This is not critical at all, just a nice to have :)
Thanks!

**Comment by dirtybit** [comment]
Hi @luispinho! 👋  

Thanks for the suggestion. We intend to use options in this extension only for options that affect code generation logic rather coding style and conventions. The reasoning behind this is to keep options as simple as possible for its users. Also, styling concerns can be addressed easily via linters and/or code formatters.

That said, I can definitely understand that teams/developers can have various preferences over coding style, this can even be a matter of controversy in the developer community sometimes. 😅 

We can keep this open for a while to get others' reaction if they have any.

Thanks again!

**Comment by luispinho** [comment]
Hello @dirtybit!
Got it, makes sense, I agree with that decision. Yup, that's what we're doing in our projects (and also why I suggested this 😅 But of course, linter with auto fixing capabilities does the trick just fine).

Indeed, for damn sure 😂

Sure thing, I'd appreciate that, maybe someone else might be looking for this. Even though I believe this would be relatively easy to implement, it might not be advisable to do (otherwise that's an entry point for other "more complex" suggestions to be implemented).

So yeah, thanks for your explanation and quick response! 😄
