### ISSUE TITLE
Package.json Zeplin Extension Model Error

### ISSUE THREAD

**Issue by destechy** [zeplin/react-native-extension#9]
"zeplin-extension-model": "git+ssh://git@github.com/zeplin/zeplin-extension-model.git#v1.x.x"
does not work.

I had to lookup zeplin extension model on npm and found this instead

"@zeplin/extension-model": "^1.1.1",

**Comment by dirtybit** [comment]
@destechy Thanks for reporting this. We've just fixed it.
